[package]
name = "web_scra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = {versio = "0.11.22", features=['blocking', 'json']}
scraper = "0.18.1"
csv = "1.3.0"